# Generated by Django 4.2.3 on 2023-07-31 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_alter_goal_options_alter_goal_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goalcomment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
