# Generated by Django 4.2.3 on 2023-08-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='user_ud',
            field=models.BigIntegerField(default=123, null=True, verbose_name='user ud'),
            preserve_default=False,
        ),
    ]
